export default [{
    'id': 1,
    'cateName': 'JAVA',
    'price': '￥100',
    'src': '/common/images/1.png',
    'pid': 1
}, {
    'id': 2,
    'cateName': 'PHP',
    'price': '￥100',
    'src': '/common/images/2.png',
    'pid': 1
}, {
    'id': 3,
    'cateName': 'C++',
    'price': '￥100',
    'src': '/common/images/3.png',
    'pid': 1
}, {
    'id': 4,
    'cateName': '书4',
    'price': '￥100',
    'src': '/common/images/1.png',
    'pid': 2
}, {
    'id': 5,
    'cateName': '书5',
    'price': '￥100',
    'src': '/common/images/1.png',
    'pid': 2
}, {
    'id': 6,
    'cateName': '书6',
    'price': '￥100',
    'src': '/common/images/1.png',
    'pid': 2
}, {
    'id': 7,
    'cateName': '书7',
    'price': '￥100',
    'src': '/common/images/1.png',
    'pid': 2
}]
